pipeline {
  agent any

  environment {
    CI = 'true'
    NEXT_TELEMETRY_DISABLED = '1'
  }

  stages {
    stage('Install Dependencies') {
      steps {
        dir('los-gehts-frontend') {
          sh 'npm ci'
        }
      }
    }

    stage('Build') {
      steps {
        sh 'npm run build'
      }
    }

    stage('Test') {
      steps {
        dir('los-gehts-frontend') {
          sh 'npm test -- --runInBand --ci'
        }
      }
    }
  }
}
